### ISSUE TITLE
Chapter 12 IronRouter problem

### ISSUE THREAD

**Issue by edyu** [DiscoverMeteor/book#146] opened 2013-12-05 03:04 UTC
I'm getting the following when I click on the individual post from the postsList template. I noticed also that the {{pathFor postsList}} in the header template also is broken in that it will point to the current page. This might be a bug in IronRouter instead of the code itself.

Exception from Deps recompute: TypeError: Object [object Object] has no method 'limit'
    at Object.Template.postsList.helpers.hasMorePosts (http://localhost:3000/client/views/posts/posts_list.js?39393fdeb8bea8d21985cb46baf9e4e1d69a791e:4:29)
    at apply (http://localhost:3000/packages/handlebars.js?c2b75d49875b4cfcc7544447aad117fd81fccf3b:276:24)
    at invoke (http://localhost:3000/packages/handlebars.js?c2b75d49875b4cfcc7544447aad117fd81fccf3b:293:18)
    at http://localhost:3000/packages/handlebars.js?c2b75d49875b4cfcc7544447aad117fd81fccf3b:385:27
    at Object.Spark.labelBranch (http://localhost:3000/packages/spark.js?3a050592ceb34d6c585c70f1df11e353610be0ab:1171:14)
    at branch (http://localhost:3000/packages/handlebars.js?c2b75d49875b4cfcc7544447aad117fd81fccf3b:355:20)
    at http://localhost:3000/packages/handlebars.js?c2b75d49875b4cfcc7544447aad117fd81fccf3b:384:20
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?13ab483e8a3c795d9991577e65e811cd0b827997:130:11)
    at template (http://localhost:3000/packages/handlebars.js?c2b75d49875b4cfcc7544447aad117fd81fccf3b:358:7) debug.js:41

**Comment by edyu** [comment] 2013-12-05 05:56
I found this problem would show up when you first go to the main list page and then click on one of the Discuss button.

**Comment by tmeasday** [comment] 2013-12-05 09:54
Hi @edyu - Do you have a `limit()` function on the `PostsListController` (in the `router.js`)?

If so, what does `Router.current()` return?

**Comment by edyu** [comment] 2013-12-05 17:42
Hi, yes I do have the limit() function. The problem exists even in the code in the book. If you launch instance on any of the code in chapter 12 and then open the javascript console, you should see it.

**Comment by craigmaslowski** [comment] 2013-12-09 22:09
I can confirm that I'm seeing the same behavior in my local app as well as the instance launched from the book.

**Comment by SachaG** [comment] 2013-12-09 22:15
We did encounter a problem with `limit()` before (it was conflicting with something), but I thought we had fixed it. I'll look into it, sorry guys!

**Comment by tmeasday** [comment] 2013-12-10 05:40
Correct me if I'm wrong @edyu but I think the `limit()` error that's thrown here is due to a mis-transcription (that's now fixed): https://github.com/DiscoverMeteor/book/issues/156, whereas the header link not working is indeed due to a IR bug (see #147)

**Closed as completed by tmeasday** 2013-12-10 05:40 UTC

**Comment by pkaushik** [comment] 2013-12-12 00:22
Problem still occurs; not a mis-transcription. Would you like me to describe steps to reproduce here or create a new issue?

**Comment by SachaG** [comment] 2013-12-12 00:28
Sure, please let us know here :)

**Comment by pkaushik** [comment] 2013-12-12 00:45
The hasMorePosts template helper from postsList is getting called twice for some reason. The following code in hasMorePosts

``` js
console.log(Router.current())
console.dir(Router.current().path)
console.log('hasMorePosts called!')
```

results in the following console output, first three lines when postsList is loaded and next three when routing away from postsList to postPage

```
/ 
Constructor
hasMorePosts called!
/posts/JMqLbQj7dTqS5qF46
Utils.extend.constructor 
hasMorePosts called!
```

**Comment by pkaushik** [comment] 2013-12-12 00:47
This is a temp workaround https://github.com/pkaushik/Microscope/commit/2fed46b2c9d5c23142ce8c36fea8fe6d00bd6eb9
